In [2]:
import numpy as np

print(np.__version__)


1.21.4


In [3]:
import numpy as np

arr = np.array(42)

print(arr)

42


In [4]:
import numpy as np

a = np.array([1,2,3])

print(a)

[1 2 3]


In [6]:
import numpy as np

a = np.array([[1,2],[3,4]])

print(a)

[[1 2]
 [3 4]]


In [7]:
import numpy as np

a = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [8]:
import numpy as np

a = np.array([1,2,3,4], ndmin=5)

print(a)

[[[[[1 2 3 4]]]]]


In [9]:
a = np.array(42)
b = np.array([1,2,3,4,5])

print(a.ndim)
print(b.ndim)

0
1


In [12]:
arr1 = np.array([1,3,5,7])

print(arr1.shape)

(4,)


In [13]:
np.zeros(2)

array([0., 0.])

In [14]:
np.ones(2)

array([1., 1.])

In [16]:
np.arange(4)

array([0, 1, 2, 3])

In [17]:
np.arange(2,9,4)

array([2, 6])

In [18]:
import numpy as np

arr = np.array(['banana','cherry','apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [19]:
import numpy as np

arr = np.array([[3,2,4],[5,0,1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [20]:
import numpy as np

arr = np.array([1,2,3,4])

print(arr[0])

1


In [21]:
data = np.array([1,2,3])

In [22]:
data[1]

2

In [23]:
data[0:2]

array([1, 2])

In [24]:
data[1:]

array([2, 3])

In [25]:
data[-2:]

array([2, 3])

In [26]:
import numpy as np

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arr[0,1,2])

6


In [27]:
import numpy as np 

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]]) 

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [30]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[1:5:2])

[2 4]


In [31]:
import numpy as np 

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]]) 

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [32]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[1:5:2])

[2 4]


In [37]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr[1,1:4])

[7 8 9]


In [38]:
import numpy as np

arr = np.array([1,2,3,40,5,40,40])

x = np.where(arr == 40)

print(x)

(array([3, 5, 6], dtype=int64),)


In [40]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8]) 

x = np.where(arr%4 == 0) 

print(x)

(array([3, 7], dtype=int64),)


In [41]:
import numpy as np

arr = np.array([6,7,9,19])

x = np.searchsorted(arr,8)

print(x)

2


In [42]:
np.searchsorted([1,2,3,4,5], 3)

2

In [43]:
np.searchsorted([1,2,3,4,5], 3, side='right')

3

In [44]:
np.searchsorted([1,2,3,4,5], [-10, 10, 2, 3])

array([0, 5, 1, 2], dtype=int64)

In [34]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr = arr.reshape(4,3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [35]:
import numpy as np

arr = np.array([[1,2,3], [4,5,6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [45]:
import numpy as np

arr = np.array([41,42,43,44])

x = [True,False,True,False]

newarr = arr[x]

print(newarr)

[41 43]


In [46]:
seq = [0, 1, 2, 3, 5, 8, 13] 

# result contains odd numbers of the list 
result = filter(lambda x: x % 2 != 0, seq) 

print(list(result)) 

[1, 3, 5, 13]


In [48]:
# result contains even numbers of the list 

result = filter(lambda x: x % 2 == 0, seq) 

print(list(result))

[0, 2, 8]


In [49]:
a = np.arange(6).reshape(2,3)

print(a)

[[0 1 2]
 [3 4 5]]


In [50]:
b = np.arange(7,13).reshape(2,3)

print(b)

[[ 7  8  9]
 [10 11 12]]


In [51]:
np.concatenate((a,b),axis=1)

array([[ 0,  1,  2,  7,  8,  9],
       [ 3,  4,  5, 10, 11, 12]])

In [52]:
np.stack((a,b))

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [53]:
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 7,  8,  9],
       [10, 11, 12]])

In [54]:
np.hstack((a,b))

array([[ 0,  1,  2,  7,  8,  9],
       [ 3,  4,  5, 10, 11, 12]])

In [55]:
np.dstack((a,b))

array([[[ 0,  7],
        [ 1,  8],
        [ 2,  9]],

       [[ 3, 10],
        [ 4, 11],
        [ 5, 12]]])